name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 18
        uses: actions/setup-java@v2
        with:
          java-version: '18'
          distribution: 'adopt'
          cache: gradle

      - name: 🔔 Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: 💪 build apk
        run: ./gradlew assembleDebug

      - run: echo "💡  build succeed."

      - name: 📸 Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: demo-apk
          path: app/build/outputs/apk/debug/app-debug.apk
